name: Build and Push gMSA Image 2022 to Docker Hub

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *' # Runs on the 1st day of every month

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the container
      run: docker build -t vrapolinario/gmsasampleapp:ltsc2022 .

    - name: Push the container
      run: docker push vrapolinario/gmsasampleapp:ltsc2022
